### PR TITLE
Update desktop palettes

### LINKED ISSUE #24: icons in “Send an image” dialog cannot be seen
See icons in the upper right corner of the image

<details>
  <summary>Catppuccin Mocha</summary>
  <br/>
  
  tmp
</details>

<details>
  <summary>Default “Night” theme</summary>
  <br/>
  
  tmp2
</details>

### LINKED ISSUE #25: Missing msgServiceBg
No colors set for `msgServiceBg` and `msgServiceSelected`.
Not sure about hover color (could not find it) maybe it's ok, maybe too light.

Mocha theme: image

### PR DESCRIPTION
**Pull request by rossnomann**
This PR makes desktop palettes more readable and adds some missing variables, such as `groupCall*`
Also  `--accent` flag is added to allow to change accent color. Green is the default accent.

Examples:

https://t.me/addtheme/ctpmochaimproved
https://t.me/addtheme/ctpmacchiatoimproved
https://t.me/addtheme/ctpfrappeimproved
https://t.me/addtheme/ctplatteimproved

Closes #24; Closes  #25;

I'm not sure what's going on in #27 but now you can change accent color.

### CODE REVIEW

**Comment by andreasgrafen** [comment]
Thanks a lot for updating the theme and fixing the mentioned issues!

image
This also seems to get rid of a lot of the contrast between the different panes which I think is not really preferential here as it makes it really hard to differentiate between the different areas used for content, navigation, etc.

This probably can easily be fixed by giving the chat area a different background (probably mantle) and highlighting pinned messages (either using crust or surface maybe?). I'm not entirely sure about the suggested solutions here tho. Open for other proposals as well. c:

**Comment by rossnomann** [comment]
My bad. There are a `wallpapper` variables in example themes, e.g. `wallpaper: t.me/bg/HsVrZS2H_FACAAAA2bSTVfYHdRQ // link to cloud wallpaper`
There are no such variables in the PR though, and Telegram will use a default wallpaper. Anyway I need to update screenshots. I will do it soon.

**Comment by rossnomann** [comment]
Updated previews along with res.webp in [5fddeb6](https://github.com/catppuccin/telegram/pull/29/commits/5fddeb689f2c7b0fcd20f9203c58e6a341b42040) . If it doesn't look good, feel free to drop this commit. 
Also it looks like preview.png is not used anymore, so I removed it.

**Comment by rossnomann** [comment]
image
I think mantle for the pinned messages and crust for the chat area are fine too. But again, there are no wallpapers in palettes and I'm not sure that I should add them.

**Comment by andreasgrafen** [comment]
> I think mantle for the pinned messages and crust for the chat area are fine too. But again, there are no wallpapers in palettes and I'm not sure that I should add them.

I would assume that most people set a separate background image anyway, so this is more of a placebo change for the most part. But for those few who are not using one this probably is a good change. c:

**Comment by rossnomann** [comment]
I think wallpapers must be added by the one who owns the cpt* themes, because cpt*improved has wallpapers uploaded by me and I don't know what can happen with that wallpapers in future.

**Comment by andreasgrafen** [comment]
I don't think the wallpaper would become inaccessible as they are simply stored on Telegram's servers. It wouldn't make much sense to tie them to a specific user account. I don't even recall specifically adding them to the current themes either.. o:

**Comment by andreasgrafen** [comment]
I hope you don't mind me pulling you in here @sgoudham. I'd like to hear your opinion on whether it's okay to eventually merge this and just have the TG Desktop theme be updated, or if there should be an effort to also edit the other themes (android, iOS, macOS) as well and release them alltogether. Personally I don't think it's an issue to update them step-by-step. but… idk.

**Comment by rossnomann** [comment]
Added wallpapers and squashed commits. That's all from my side, I guess.

**Comment by andreasgrafen** [comment]
Again; Thank you so much for your contributions!

**Comment by sgoudham** [comment]
> I hope you don't mind me pulling you in here @sgoudham. I'd like to hear your opinion on whether it's okay to eventually merge this and just have the TG Desktop theme be updated, or if there should be an effort to also edit the other themes (android, iOS, macOS) as well and release them alltogether. Personally I don't think it's an issue to update them step-by-step. but… idk.

No worries about the ping.

I suppose I don't have enough knowledge on how _easy_ it is to edit the other themes alongside the desktop one but I'd imagine it's annoying since the contributor hasn't attempted it already. (or maybe they aren't interested)

Ultimately, if it requires slight updates here and there then I don't mind this PR staying open for a bit longer but if there're a lot of changes to be made or if there's relatively little interest in it right now, we can totally merge this PR, raise issues to track the updates to the mobile versions and update them "step-by-step" as you mentioned.

I'd definitely like to avoid this PR going stale for a long period of time 👍

**Comment by sgoudham** [comment]
While I'm here, a slight request from me, could we document the release process for the theme in another PR/commit? 
It's not obvious to me when looking at the README or the repository structure.

**Comment by andreasgrafen** [comment]
From what I've experienced with this in the past it's really annoying to convert the themes between the different versions of Telegram since the naming conventions between the different template files are vastly different. Telegram offers a tool that's supposed to convert themes, but this also doesn't seem to work properly..
My initial assessment is that it seems to be a lot of effort to get the other themes updated to the same state. Hence I'm tempted to just merge this and leave the conversion for later. Glad you agree with that. c:

The release process with Telegram themes is equally annyoing.. since right now they're tied to my personal Telegram account.. iirc there is a way to distribute themes as plain old files, but I haven't really looked into that too much but it might be a good alternative to the current link-based distribution.

**Comment by andreasgrafen** [comment]
I've been test-driving this for a couple days and haven't found any bugs or quirks so far. I've upstreamed these changes; so the quote-unquote *official* links are up to date with this now. c:

**Comment by andreasgrafen** [comment]
Oh, that's odd. On my end I don't even get a green scrollbar in the first place.
tg-scroll

I have initially distributed the themes through the themes website and have just updated the contents again. If this issue persists on your end; may I ask what platform and version you're on; maybe the issue is burried in there somewhere?

> MacOS 14.2.1 (M2) – Telegram Desktop 4.16.8

**Comment by rossnomann** [comment]
image
Telegram Desktop 4.16.8 (downloaded from the official website)
Ubuntu 22.04 on Xorg

**Comment by isabelincorp** [comment]
Thank you both for your work on this theme! I love the work being done, just one suggestion I have is using subtext colors rather than all text for when you're on the main menu page with all the messages. Changing it over to subtext would make more sense.

What I mean is making the message preview not the same color as the channel name. 

Telegram Desktop 4.16.8 (arch repo)
Arch on Wayland (sway/wlroots)

image

**Pull request merged**
