### PR TITLE
Fix macos files

### PR DESCRIPTION
**Pull request by khalangy**
Replace : by = and remove comments at end lines

### CODE REVIEW

**Comment by NamesCode** [comment]
Can't seem to get this to work for me? Have you tested this yourself? If so could you walk me through how you have?

**Comment by khalangy** [comment]
Yes I use it on my Macbook Pro M1 MacOs 13.1 (22C65)
Telegram version 9.3.1.241825 Stable
For testing, you have to : 
- Download the macos file from my branch for example for frappe taste : https://raw.githubusercontent.com/khalangy/telegram-catppuccin/update-macos/src/frappe/macos
- Rename it with extention .palette
- Create a new theme in telegram
- Edit the theme created and select the .palette file you just downloaded

**Comment by Defman21** [comment]
This **might** break the theme in the [Qt client](https://desktop.telegram.org/) (the cross-platform one) while work with the [MacOS](https://macos.telegram.org/) native one.

**Comment by AlexNabokikh** [comment]
Will this ever be merged?

**Pull request merged**
